app/__init__.py
from flask_bootstrap import Bootstrap
from flask.app import Flask
from flask_sqlalchemy import SQLAlchemy
from settings import config 

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    bootstrap.init_app(app)
    db.init_app(app)
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    return app
    

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors

app/main/views.py
'''
Created on 2017年3月19日

@author: chaohu
'''
from flask.globals import request, session
from flask.helpers import make_response, url_for, flash
from werkzeug.utils import redirect
from flask_wtf.form import Form
from wtforms.fields import StringField, PasswordField, SubmitField
from wtforms.validators import Required
from flask.templating import render_template
from . import main
from app.migrations.models import UserInfo

@main.route("/")
def index():
#     user_agent = request.headers.get("User-Agent")
#     resp = make_response("<h4>test flask in '%s'</h4>" % user_agent)
    name = session['name']
    return render_template('index.html',name=name)

@main.route("/wm/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        name = session['name'] =form.name.data
#         user = UserInfo.query(name).first()
        user = None
        password = form.password.data
#         if user is not None and user.password == password:
        if True:
            return redirect(url_for('main.index'))
        flash('密码错误')
    return render_template('login.html', form=form,
                           name=session.get('name'))
@main.route("/wm/logout", methods=['GET', 'POST'])
def logout():
    flash('you have been logged out')
    session['name'] = None
    return redirect(url_for('main.index'))
    
class LoginForm(Form):
    name = StringField('帐号：', validators=[Required()])
    password = PasswordField('密码：', validators=[Required()])
    submit = SubmitField("登录")

app/templates/base.html
<!DOCTYPE html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="author" content="chaohu" />
{% extends "bootstrap/base.html" %} 
{% block title %}WM{% endblock %}
{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{url_for('static',filename='favicon.ico')}}"
 type="image/x-icon">
<link rel="icon" href="{{url_for('static',filename='wm_48.ico')}}"
 type="image/x-icon">
{% endblock %}
{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span> 
				<span class="icon-bar"></span>
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">WM</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="/">首页</a></li>
				<li><a href="/">设置</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{%if name %}
				<li><a href="{{ url_for('main.logout')}}">退出</a></li>
				{% else %}
				<li><a href="/wm/login">登录</a></li>
<!-- 				<li><a href="/wm/login">注册</a></li> -->
				{%endif %}
			</ul>
		</div>
	</div>
</div>
{% endblock %} 
{% block content %}
<div class="container">
	{% for message in get_flashed_messages() %}
	<div class="alert alert-warning">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  {{ message }}
	</div>
	{% endfor %}
	
    {% block page_content%}{%endblock%}
</div>
{% endblock %}
</html>

app/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="author" content="chaohu" />
{% extends "base.html" %} {% block title %}首页 - WM{% endblock
%} {% block page_content %}
<div class="page-header">
	<h1>Hello,{%if name %} {{ name }}
	{% else %}Stranger<small>,&nbsp;
	<a href="/wm/login">请登录</a></small>
	</h1>
	{% endif %}
	<ul>
		{% for rcd in records %}
		<li>{{rcd}}</li> 
		{% endfor %}
	</ul>
</div>
{% endblock %}
</html>

app/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="author" content="chaohu" />
{% extends "base.html" %} 
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}首页 - WM{% endblock %} 
{% block page_content %}
<div class="page-header">
<!-- <form method="post"> -->
<!-- 	<ul> -->
<!-- 		<li>{{ form.hidden_tag() }}</li> -->
<!-- 		<li>{{ form.name.label}}{{ form.name() }}</li> -->
<!-- 		<li>{{ form.password.label}}{{ form.password() }}</li> -->
<!-- 		<li>{{ form.submit()}}</li>  -->
<!-- 	</ul> -->
<!-- </form> -->
<!-- 	<h1>Hello,{%if name %} {{ name }} -->
<!-- 	{% else %}Stranger{% endif %}!</h1> -->
</div>
{{ wtf.quick_form(form) }}
{% endblock %}
</html>